server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/josembarreda/Bootcamp-ConfigServer.git
          default-label: main
          search-paths:
          - '*service'